services:
  # postgresdb:  # Uncomment to connect a Postgres DB
  #   image: postgres
  #   environment:
  #     POSTGRES_PASSWORD: secret
  wallet-api:
    image: waltid/wallet-api@sha256:bee553f2b6a3df9ea48a2371e2848f3dca5921032602ec2c03e5256d80cf92d8
    volumes:
      - ./wallet-api/config:/waltid-wallet-api/config
      - ./wallet-api/walt.yaml:/waltid-wallet-api/walt.yaml
      - ./wallet-api/data:/waltid-wallet-api/data

  issuer-api:
    platform: linux/x86_64
    image: waltid/issuer-api@sha256:49f2094ace71a393b30df3b2a06ca415485ede483e0682f1599af14e3be9a820
    volumes:
      - ./issuer-api/config:/waltid-issuer-api/config

  verifier-api:
    platform: linux/x86_64
    image: waltid/verifier-api@sha256:321a363a0fdc6afccae38a736f745d190c0960b04c31de436e41aa5a320d255f
    volumes:
      - ./verifier-api/config:/waltid-verifier-api/config

  waltid-web-wallet:
    image: waltid/waltid-web-wallet@sha256:615304cd46ea589ff1cd3a3d24658b4587fa4470e6af0a385da814cb35cff6ab
    environment:
      NUXT_PUBLIC_ISSUER_CALLBACK_URL: "http://localhost:$WALLET_FRONTEND_PORT"
      PORT: $WALLET_FRONTEND_PORT

  web-portal:
    platform: linux/x86_64
    image: waltid/portal@sha256:9c32d67d1686fd4c0f2a64523310968c3e54287dba117cd34ede3ce92276d675
    environment:
      NEXT_PUBLIC_VC_REPO: "http://localhost:$VC_REPO_PORT"
      NEXT_PUBLIC_ISSUER: "http://localhost:$ISSUER_API_PORT"
      NEXT_PUBLIC_VERIFIER: "http://localhost:$VERIFIER_API_PORT"
      NEXT_PUBLIC_WALLET: "http://localhost:$WALLET_FRONTEND_PORT"
      PORT: $WEB_PORTAL_PORT

  vc-repo:
    platform: linux/x86_64
    image: waltid/vc-repository@sha256:0a49c14c2c5c777c5a446a44874c668f16fbaca91f1ab21ad8522d86b67ca996
    environment:
      PORT: $VC_REPO_PORT

  caddy:
    image: caddy@sha256:2a0d069ea95d91641d201943a5a049e83cbfade8039670aebfb441b132189de6
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:

      - target: $WALLET_BACKEND_PORT
        published: $WALLET_BACKEND_PORT # wallet-api
        protocol: tcp
        mode: host

      - target: $ISSUER_API_PORT
        published: $ISSUER_API_PORT # issuer-api
        protocol: tcp
        mode: host

      - target: $VERIFIER_API_PORT
        published: $VERIFIER_API_PORT # verifier-api
        protocol: tcp
        mode: host

      - target: $WALLET_FRONTEND_PORT
        published: $WALLET_FRONTEND_PORT # waltid-web-wallet
        protocol: tcp
        mode: host

      - target: $WEB_PORTAL_PORT
        published: $WEB_PORTAL_PORT # web-portal
        protocol: tcp
        mode: host

      - target: $VC_REPO_PORT
        published: $VC_REPO_PORT # vc-repo
        protocol: tcp
        mode: host

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
